apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: tracer-runner
  namespace: arc-runners
spec:
  replicas: 1
  template:
    spec:
      labels:
        - tracer-runner
      repository: harden-runner-canary/arc-tracer-benchmark