name: Caller Workflow

on:
  workflow_dispatch:


jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reu.yml
    secrets: inherit  # Passes ALL secrets from the caller workflow to the reusable workflow
