name: hello-world
on: push
permissions:
  contents: read

jobs:

  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Harden-Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # int

      - name: my-step
        run: echo "Hello World!"