name: hello-world
on: push
permissions:
  contents: read

jobs:

  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Harden-Runner
        uses: step-security/harden-runner@f1db3319d7db49c70352da1f5d1a122f754e8c01 # int

      - run: wget https://httpbin.org/get

      - name: my-step
        run: echo "Hello World!"