name: hello-world
on: push
jobs:

  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Harden-Runner
        uses: step-security/harden-runner@int

      - name: my-step
        run: echo "Hello World!"