# Workflow to reproduce "Verifying URN" step
name: Maven Dependency Verification

on:
  workflow_dispatch:

jobs:
  build-with-verification:
    runs-on: ubuntu-latest
    
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit # Start with audit to see network calls
        
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Create Maven project structure
      run: |
        mkdir -p src/main/java/com/example
        mkdir -p src/test/java/com/example
        
        # Create a simple Java class
        cat > src/main/java/com/example/App.java << 'EOF'
        package com.example;
        
        import org.apache.commons.lang3.StringUtils;
        import org.slf4j.Logger;
        import org.slf4j.LoggerFactory;
        
        public class App {
            private static final Logger logger = LoggerFactory.getLogger(App.class);
            
            public static void main(String[] args) {
                logger.info("Hello World: {}", StringUtils.capitalize("hello"));
            }
        }
        EOF
        
        # Create a test class
        cat > src/test/java/com/example/AppTest.java << 'EOF'
        package com.example;
        
        import org.junit.jupiter.api.Test;
        import static org.junit.jupiter.api.Assertions.*;
        
        public class AppTest {
            @Test
            public void testApp() {
                assertTrue(true);
            }
        }
        EOF
        
    - name: Create pom.xml with dependency verification
      run: |
        cat > pom.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <project xmlns="http://maven.apache.org/POM/4.0.0"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            
            <groupId>com.example</groupId>
            <artifactId>verification-test</artifactId>
            <version>1.0-SNAPSHOT</version>
            <packaging>jar</packaging>
            
            <properties>
                <maven.compiler.source>11</maven.compiler.source>
                <maven.compiler.target>11</maven.compiler.target>
                <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
            </properties>
            
            <dependencies>
                <!-- Dependencies that will trigger verification -->
                <dependency>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-lang3</artifactId>
                    <version>3.12.0</version>
                </dependency>
                
                <dependency>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                    <version>2.0.7</version>
                </dependency>
                
                <dependency>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                    <version>1.4.8</version>
                </dependency>
                
                <dependency>
                    <groupId>org.junit.jupiter</groupId>
                    <artifactId>junit-jupiter</artifactId>
                    <version>5.9.3</version>
                    <scope>test</scope>
                </dependency>
            </dependencies>
            
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>3.11.0</version>
                    </plugin>
                    
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>3.1.2</version>
                    </plugin>
                    
                    <!-- OWASP Dependency Check - likely source of "Verifying URN" -->
                    <plugin>
                        <groupId>org.owasp</groupId>
                        <artifactId>dependency-check-maven</artifactId>
                        <version>8.4.0</version>
                        <configuration>
                            <failBuildOnCVSS>7</failBuildOnCVSS>
                            <suppressionFiles>
                                <suppressionFile>owasp-suppressions.xml</suppressionFile>
                            </suppressionFiles>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    
                    <!-- Maven Enforcer with digest rules -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-enforcer-plugin</artifactId>
                        <version>3.4.1</version>
                        <executions>
                            <execution>
                                <id>enforce-dependency-integrity</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>enforce</goal>
                                </goals>
                                <configuration>
                                    <rules>
                                        <requireMavenVersion>
                                            <version>[3.6.0,)</version>
                                        </requireMavenVersion>
                                        <requireJavaVersion>
                                            <version>[11,)</version>
                                        </requireJavaVersion>
                                        <bannedDependencies>
                                            <excludes>
                                                <exclude>commons-logging</exclude>
                                                <exclude>log4j:log4j</exclude>
                                            </excludes>
                                        </bannedDependencies>
                                    </rules>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    
                    <!-- Versions plugin to check for updates -->
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>versions-maven-plugin</artifactId>
                        <version>2.16.0</version>
                        <executions>
                            <execution>
                                <phase>verify</phase>
                                <goals>
                                    <goal>display-dependency-updates</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </project>
        EOF
        
    - name: Create OWASP suppression file
      run: |
        cat > owasp-suppressions.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <suppressions xmlns="https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd">
            <!-- Add suppressions here if needed -->
        </suppressions>
        EOF
        
    - name: Build with Maven (verbose output)
      run: |
        echo "Starting Maven build with dependency verification..."
        mvn clean verify -X -e \
          -Dmaven.wagon.http.connectionTimeout=10000 \
          -Dmaven.wagon.http.readTimeout=30000 \
          2>&1 | tee maven-build.log
          
    - name: Search for URN verification messages
      run: |
        echo "=== Searching for URN-related messages ==="
        grep -i "urn\|verifying\|verify" maven-build.log || echo "No URN messages found"
        
        echo "=== Searching for dependency check messages ==="
        grep -i "dependency.check\|vulnerability\|cve" maven-build.log || echo "No dependency check messages found"
        
        echo "=== Looking for network-related timeouts or slow operations ==="
        grep -i "timeout\|slow\|downloading\|downloaded" maven-build.log || echo "No timeout messages found"
        
    - name: Run OWASP Dependency Check separately with verbose output
      run: |
        echo "Running OWASP Dependency Check with maximum verbosity..."
        mvn org.owasp:dependency-check-maven:8.4.0:check -X -e \
          -Dformat=XML,HTML,JSON \
          2>&1 | tee dependency-check.log
          
    - name: Search dependency check logs for URN messages
      run: |
        echo "=== Searching dependency check logs for URN messages ==="
        grep -i "urn\|verifying\|verify" dependency-check.log || echo "No URN messages in dependency check"
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: |
          maven-build.log
          dependency-check.log
          target/dependency-check-report.html
          target/dependency-check-report.xml
