name: Testing File Config
on:
  workflow_dispatch:
    inputs:
      EksConfigFile:
        description: "File for EKSConfig"
        required: false
        type: string
        default: "default.yml"
      
permissions:
  contents: read

jobs:

  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Harden-Runner
        uses: step-security/harden-runner@f1db3319d7db49c70352da1f5d1a122f754e8c01 # int

      - name: my-step
        run: echo "Hello World!"
      

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install yq for YAML manipulation
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y

      - name: Load EKSConfigFile Configuration
        run: |
          KUBERNETES_VERSION=$(yq '.KubernetesVersion.value' "$inputs.EksConfigFile")
          AMI_TYPE=$(yq '.AMIType.value' "$inputs.EksConfigFile")

          echo "KUBERNETES_VERSION=$KUBERNETES_VERSION" >> $GITHUB_ENV
          echo "AMI_TYPE=$AMI_TYPE" >> $GITHUB_ENV
      
      - name: Output Values
        run: |
            echo "Kubernetes Version: ${{ env.KUBERNETES_VERSION }}"
            echo "AMI Type: ${{ env.AMI_TYPE }}"
    