name: Testing File Config
on:
  workflow_dispatch:
    inputs:
      EksConfigFile:
        description: "File for EKSConfig"
        required: false
        type: string
        default: "default.yml"
      
      ArcConfig:
        description: "Config for ARC Harden Runner"
        required: true
        type: string
        default: '{"ClusterWidePolicyFile" : "","ARCHardenRunnerReleaseBranch" : "int"}'
      
permissions:
  contents: read

jobs:

  my-job:
    runs-on: ubuntu-latest
    steps:

      - name: my-step
        run: echo "Hello World!"
      

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Install yq for YAML manipulation
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
          sudo chmod +x /usr/bin/yq

      - name: Load EKSConfigFile Configuration
        run: |
          CONFIG_FILE="${{ inputs.EksConfigFile }}"
          KUBERNETES_VERSION=$(yq '.KubernetesVersion.value' "$CONFIG_FILE")
          AMI_TYPE=$(yq '.AMIType.value' "$CONFIG_FILE")

          echo "KUBERNETES_VERSION=$KUBERNETES_VERSION" >> $GITHUB_ENV
          echo "AMI_TYPE=$AMI_TYPE" >> $GITHUB_ENV

          ARC_CONFIG_JSON='${{ inputs.ArcConfig }}'
          ClusterWidePolicyFile=$(echo "$ARC_CONFIG_JSON" | jq -r '.ClusterWidePolicyFile')
          ARCHardenRunnerReleaseBranch=$(echo "$ARC_CONFIG_JSON" | jq -r '.ARCHardenRunnerReleaseBranch')

          echo "ClusterWidePolicyFile=$ClusterWidePolicyFile" >> $GITHUB_ENV
          echo "ARCHardenRunnerReleaseBranch=$ARCHardenRunnerReleaseBranch" >> $GITHUB_ENV
      
      - name: Output Values
        run: |
            echo "Kubernetes Version: ${{ env.KUBERNETES_VERSION }}"
            echo "AMI Type: ${{ env.AMI_TYPE }}"
            echo "ClusterWidePolicyFile: ${{ env.ClusterWidePolicyFile }}"
            echo "ARCHardenRunnerReleaseBranch: ${{ env.ARCHardenRunnerReleaseBranch }}"
    