name: Testing File Config
on:
  workflow_dispatch:
    inputs:
      EksConfigFile:
        description: "File for EKSConfig"
        required: false
        type: string
        default: "default.yml"
      
      ArcConfigFile:
        description: "Config for ARC Harden Runner"
        required: true
        type: string
        default: 'arc_config/default.json'
      
permissions:
  contents: read

jobs:

  my-job:
    runs-on: ubuntu-latest
    outputs:
      KUBERNETES_VERSION: ${{ steps.load_config.outputs.KUBERNETES_VERSION }}
      AMI_TYPE: ${{ steps.load_config.outputs.AMI_TYPE }}
      ClusterWidePolicyFile: ${{ steps.load_config.outputs.ClusterWidePolicyFile }}
      ARCHardenRunnerReleaseBranch: ${{ steps.load_config.outputs.ARCHardenRunnerReleaseBranch }}
    steps:

      - name: my-step
        run: echo "Hello World!"
      

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Install yq for YAML manipulation
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
          sudo chmod +x /usr/bin/yq

      - name: Load EKSConfigFile Configuration
        id: load_config
        run: |
          CONFIG_FILE="${{ inputs.EksConfigFile }}"
          KUBERNETES_VERSION=$(yq '.KubernetesVersion.value' "$CONFIG_FILE")
          AMI_TYPE=$(yq '.AMIType.value' "$CONFIG_FILE")

          echo "KUBERNETES_VERSION=$KUBERNETES_VERSION" >> $GITHUB_ENV
          echo "KUBERNETES_VERSION=$KUBERNETES_VERSION" >> $GITHUB_OUTPUT
          echo "AMI_TYPE=$AMI_TYPE" >> $GITHUB_ENV
          echo "AMI_TYPE=$AMI_TYPE" >> $GITHUB_OUTPUT

          ARC_CONFIG_FILE='${{ inputs.ArcConfigFile }}'
          ClusterWidePolicyFile=$(jq -r '.ClusterWidePolicyFile' "$ARC_CONFIG_FILE")
          ARCHardenRunnerReleaseBranch=$(jq -r '.ARCHardenRunnerReleaseBranch' "$ARC_CONFIG_FILE")

          echo "ClusterWidePolicyFile=$ClusterWidePolicyFile" >> $GITHUB_ENV
          echo "ClusterWidePolicyFile=$ClusterWidePolicyFile" >> $GITHUB_OUTPUT
          echo "ARCHardenRunnerReleaseBranch=$ARCHardenRunnerReleaseBranch" >> $GITHUB_ENV
          echo "ARCHardenRunnerReleaseBranch=$ARCHardenRunnerReleaseBranch" >> $GITHUB_OUTPUT
      
      - name: Output Values
        run: |
            echo "Kubernetes Version: ${{ env.KUBERNETES_VERSION }}"
            echo "AMI Type: ${{ env.AMI_TYPE }}"
            echo "ClusterWidePolicyFile: ${{ env.ClusterWidePolicyFile }}"
            echo "ARCHardenRunnerReleaseBranch: ${{ env.ARCHardenRunnerReleaseBranch }}"


  output-job:
      needs: [my-job]
      runs-on: ubuntu-latest
      steps:
        - name: Output Values
          run: |
              echo "Kubernetes Version: ${{ needs.my-job.outputs.KUBERNETES_VERSION }}"
              echo "AMI Type: ${{ needs.my-job.outputs.AMI_TYPE }}"
              echo "ClusterWidePolicyFile: ${{ needs.my-job.outputs.ClusterWidePolicyFile }}"
              echo "ARCHardenRunnerReleaseBranch: ${{ needs.my-job.outputs.ARCHardenRunnerReleaseBranch }}"
